---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: omero-server-py2py3
    image: centos/systemd
    image_version: latest
    command: /sbin/init
    privileged: true
    groups:
      - docker-hosts
      - omero-py3
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    v: true
    diff: true
    # tags: [x]
  playbooks:
    # TODO: Use shared test playbooks
    prepare: ../resources/install-oldomero.yml
    converge: ../resources/playbook-py3.yml
  inventory:
    host_vars:
      omero-server-py2py3:
        postgresql_version: "10"
scenario:
  name: upgrade-py2py3
  converge_sequence:
    - converge

verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
